name: th1-frontend
services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: .
      args:
        OAUTH_URL: ${OAUTH_URL}
        OAUTH_REALM: ${OAUTH_REALM}
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
        OAUTH_ENABLED: ${OAUTH_ENABLED}
    ports:
      - "127.0.0.1:5173:80"
    environment:
      - API_HOST=${API_HOST}
      - METABASE_HOST=${METABASE_HOST}
