# removeHeaderSettings:
type: object
required:
  - enabled
  - threshold
  - blockList
properties:
  enabled:
    type: boolean
    default: true
  threshold:
    type: integer
    minimum: 0
  blockList:
    type: array
    items:
      type: string
      minLength: 1