name: Deploy to dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yaml
  docker:
    needs: verify
    uses: ./.github/workflows/docker.yaml
  deploy:
    needs: docker
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Perform deploy requests
        run: |
          file=$(curl -s ${{ secrets.API_HOST }}/api/stacks/${{ secrets.STACK_ID }}/file \
            -H "X-API-KEY: ${{ secrets.API_KEY }}" | jq '.StackFileContent')
          stackenv=$(curl -s ${{ secrets.API_HOST }}/api/stacks/${{ secrets.STACK_ID }} \
            -H "X-API-KEY:${{ secrets.API_KEY }}" | jq '.Env')

          wrapped=$(jq -n --argjson file "$file" --argjson stackenv "$stackenv" --argjson id "${{ secrets.STACK_ID }}" '{Env:$stackenv,id:$id,Prune:false,PullImage:true,StackFileContent: $file}')

          curl -X PUT -s ${{ secrets.API_HOST }}/api/stacks/${{ secrets.STACK_ID }}?endpointId=${{ secrets.ENDPOINT_ID }} \
            -H "Content-Type: application/json" \
            -H "X-API-KEY: ${{ secrets.API_KEY }}" \
            -d "$wrapped" > /dev/null
