spring:
  application:
    name: th1
  threads:
    virtual:
      enabled: false
  datasource:
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          create_namespaces: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080
th1:
  mb:
    api:
      key: <key>
      general-key: <key>
    base-path: http://example.com:3000/api
  security:
    allowed-origins:
      - "*"
  snapshot:
    dir: /app/snapshots

springdoc:
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
